language: php

php:
 - 5.6

before_script:
 - wget http://getcomposer.org/composer.phar
 - php composer.phar install --dev --no-interaction
 - if [[ $(phpenv version-name) == '5.6' ]]; then composer require satooshi/php-coveralls:dev-master -n ; fi
 - if [[ $(phpenv version-name) != '5.6' ]]; then composer install -n ; fi
 - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest --prefer-stable -n; fi;

script:
 - mkdir -p build/logs
 - phpunit --coverage-clover build/logs/clover.xml
 - if [[ $(phpenv version-name) == '5.6' ]]; then vendor/bin/phpunit --coverage-clover clover.xml ; fi
 - if [[ $(phpenv version-name) != '5.6' ]]; then vendor/bin/phpunit ; fi

after_script:
 - php vendor/bin/coveralls -v
 - if [[ $(phpenv version-name) == '5.6' ]]; then php vendor/bin/coveralls -v ; fi
