language: php
sudo: required

php:
 - 5.6

before_script:
 - wget http://getcomposer.org/composer.phar
 - sudo apt-get install poppler-utils
 - php composer.phar install --dev --no-interaction
 - composer require satooshi/php-coveralls:dev-master -n

script:
 - mkdir -p build/logs
 - phpunit --coverage-clover build/logs/clover.xml

after_script:
 - php bin/coveralls -v
